name: SpyNetherPortals
version: 1.0.0
main: com.spygamingog.spynetherportals.SpyNetherPortals
api-version: '1.21'
author: SpyGamingOG
depend: [SpyCore]
description: Connects worlds via nether and end portals based on naming conventions.
